apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mywebapp-helm.fullname" . }}-header  # Use fullname helper for name
data:
  headerText: "Welcome to My Custom Web App!"  # Pull from values.yaml
