apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mywebapp-helm.fullname" . }}-ingress  # Append -ingress to the fullname
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mywebapp.local  # Ensure you set this in values.yaml or customize here
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "mywebapp-helm.fullname" . }}  # Use consistent service name
            port:
              number: 80
