apiVersion: v1
kind: Service
metadata:
  name: {{ include "mywebapp-helm.fullname" . }}  # Use helper template for name
spec:
  selector:
    app: {{ include "mywebapp-helm.fullname" . }}  # Consistent name across resources
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
